### ISSUE TITLE
error when invoking .swap()

### ISSUE THREAD

**Issue by cryptoB0T** [fun-xyz/funkit-react#29]
error when performing a swap:
`funWallet.swap()`

steps to reproduce:
https://codesandbox.io/p/github/TheFunGroup/Action-Web-Demo/

- complete steps 1-4

expected: 
step 4 will perform swap 

actual: 
API returns a 500

response from API:
```json
 {
  "errorMsg": "Failed to send userOp: UserOperation reverted during simulation with reason: AA25 invalid account nonce",
  "errorCode": "UserOpFailureError",
  "reqId": "bc842d2d-e888-45bb-be46-7a101b8a0d4b"
}
```

**Comment by NightTrek** [comment]
Thank you for the report. It seems like this was an API / Backend issue. We resolved the problem without any SDK changes. Thank you for reporting it.
